colors:
  H1:
    alpha: "#543005"
    beta: "#8c510a"
    gamma: "#80cdc1" 
    gamma.1: "#80cdc1"
    gamma.2: "#70cdc1" # FIXME: this is arbitrary
    gamma.3: "#60cdc1" # FIXME: this is arbitrary
    gamma2: "#35978f"
    pandemic: "#01665e"
    gamma2-beta-like: "#8c000a"
    delta1: "#bf812d"
    delta1a: "#dfc27d"
    delta1b: "#f6e8c3"
    delta2: "#c7eae5"
    H4: "#FF0000"
#    No_data: "#EDF8B1"
  H3: 
    2010.1: "#999999"
    2010.2: "#996633"
    other-human: "#F90005"
    I: "#542788"
    II: "#d73027"
    III: "#2166AC"
    IV: "#E69F00"
    IV-A: "#56B4E9"
    IV-B: "#009E73"
    IV-B1: "#009E73"
    IV-B2: "#009E73"
    IV-C: "#F0E442"
    IV-D: "#0072B2"
    IV-E: "#D55E00"
    IV-F: "#CC79A7"
    IV-G: "#66FF99"
    IV-H: "#FFB3E6"
    IV-I: "#9966FF"
    IV-J: "#CCFF66"
    IV-K: "#66CCFF"
    H4: "#FF0000"
#    No_data: "#EDF8B1"
  N1:
    Classical: "#FEB24C"
    Pandemic: "#F03B20"
    Human_seasonal: "#BD2D2B"
    MN99: "#91BFDB"
    N6: "#FF0000"
#    No_data: "#EDF881"
  N2:
    2002: "#FF42A4"
    2002A: "#008EFF"
    2002B: "#00CCFF"
    1998: "#007F00"
    1998A: "#00B122"
    1998B: "#00DC4F"
    2002A1: "#987FFF"
    2002A2: "#E049FF"
    2002B1: "#0059FF"
    2002B2: "#0093FF"
    02: "#FF42A4"
    02A: "#008EFF"
    02B: "#00CCFF"
    98: "#007F00"
    98A: "#00B122"
    98B: "#00DC4F"
    02A1: "#987FFF"
    02A2: "#E049FF"
    02B1: "#0059FF"
    02B2: "#0093FF"
    Human-to-swine_2016: "#1F38FF"
    Human-like_2010.2: "#996633"
    2016: "#996633"
    Human-like: "#969696"
    Human_N2: "#969696"
    TX98: "#FF9F02"
    unknown: "#800000"
#    No_data: "#EDF8B1"
  PB2:
    PDM: "#762A83"
    TRIG: "#C2A5CF"
    TX98: "#C7EAE5"
    Human-seasonal: "#969696"
    Human-seasonal_H3: "#969696"
    classicalSwine: "#FF0000"
    unknown: "#800000"
  PB1:
    PDM: "#762A83"
    TRIG: "#C2A5CF"
    TX98: "#C7EAE5"
    Human-seasonal: "#969696"
    Human-seasonal_H3: "#969696"
    classicalSwine: "#FF0000"
    unknown: "#800000"
  PA:
    PDM: "#762A83"
    TRIG: "#C2A5CF"
    TX98: "#C7EAE5"
    Human-seasonal: "#969696"
    Human-seasonal_H3: "#969696"
    classicalSwine: "###FF0000"
    unknown: "#800000"
  NP:
    PDM: "#762A83"
    TRIG: "#C2A5CF"
    TX98: "#C7EAE5"
    Human-seasonal: "#969696"
    Human-seasonal_H3: "#969696"
    classicalSwine: "#FF0000"
    unknown: "#800000"
  M:
    PDM: "#762A83"
    TRIG: "#C2A5CF"
    TX98: "#C7EAE5"
    Human-seasonal: "#969696"
    Human-seasonal_H3: "#969696"
    classicalSwine: "#FF0000"
    unknown: "#800000"
  NS:
    PDM: "#762A83"
    TRIG: "#C2A5CF"
    TX98: "#C7EAE5"
    Human-seasonal: "#969696"
    Human-seasonal_H3: "#969696"
    classicalSwine: "#FF0000"
    unknown: "#800000"
  Subtype:
    H1N1: "#D7191C"
    H1N2: "#FDAE61"
    H3: "#FFFFBF"
    H3N1: "#ABD9E9"
    H3N2: "#2C7FB8"
    mixed: "#E0F3F8"
    H4N6: "#FF0000"
