colors:
  Subtype:
    H1N1: "#D7191C"
    H1N2: "#FDAE61"
    H3: "#FFFFBF"
    H3N1: "#ABD9E9"
    H3N2: "#2C7FB8"
    mixed: "#E0F3F8"
    H4N6: "#FF0000"
  H1:
    1A.1: "#64B5F6"
    alpha: "#64B5F6"
    1A.1.1: "#29B6F6"
    1A.1.1.1: "#00BCD4"
    alpha-1: "#00BCD4"
    1A.1.1.2: "#0097A7"
    alpha-2: "#0097A7"
    1A.1.1.3: "#00897B"
    alpha-del: "#00897B"
    1A.1.2: "#00695C"
    1A.1.3: "#004D40"
    1A.1.4: "#311B92"
    1A.2: "#4527A0"
    beta: "#4527A0"
    1A.3: "#5E35B1"
    1A.3.1: "#7E57C2"
    1A.3.2: "#3F51B5"
    gamma2: "#3F51B5"
    1A.3.3: "#283593"
    1A.3.3.1: "#01579B"
    1A.3.3.2: "#0277BD"
    pdm: "#0277BD"
    PDM: "#0277BD"
    pandemic: "#0277BD"
    Pandemic: "#0277BD"
    1A.3.3.3: "#1976D2"
    gamma: "#1976D2"
    1A.3.3.3-c1: "#2196F3"
    gamma-c1: "#2196F3"
    1A.3.3.3-c2: "#03A9F4"
    gamma-c2: "#03A9F4"
    1A.3.3.3-c3: "#4DB6AC"
    gamma-c3: "#4DB6AC"
    1A.3.3.4: "#BA68C8"
    1A.4: "#9C27B0"
    LAIV: "#9C27B0"
    1A.5: "#7B1FA2"
    1A.5.1: "#880E4F"
    1A.5.2: "#C2185B"
    1A.5.3: "#E91E63"
    1B.1: "#689F38"
    1B.1.1: "#388E3C"
    1B.1.2: "#2E7D32"
    1B.1.2.1: "#2E7D32"
    1B.1.2.2: "#1B5E20"
    1B.1.2.3: "#1B5E20"
    1B.2.1: "#43A047"
    delta2: "#43A047"
    1B.2.2: "#66BB6A"
    delta1: "#66BB6A"
    1B.2.2.1: "#AFB42B"
    delta1a: "#AFB42B"
    1B.2.2.2: "#CDDC39"
    delta1b: "#CDDC39"
    1B.2.3: "#FFD54F"
    1B.2.4: "#F9A825"
    1B.2.5: "#FF8F00"
    1B.3: "#FFB300"
    1C.1: "#F4511E"
    1C.2: "#D84315"
    1C.2.1: "#E65100"
    Eurasian_avian-like: "#E65100"
    Eurasian avian-like: "#E65100"
    1C.2.2: "#F57C00"
    1C.2.3: "#FF9800"
    1C.2.4: "#FFB74D"
    1C.2.5: "#8D6E63"
    1C.2.6: "#5D4037"
    Other-Avian: "#9E9E9E"
    Other-Human: "#546E7A"
    Other-Human-1B.2: "#757575"
  H3:
    1970.1: "#9C27B0"
    1980.1: "#6A1B9A"
    1990.1: "#880E4F"
    LAIV: "#880E4F"
    1990.2: "#D81B60"
    1990.3: "#EC407A"
    1990.5: "#E53935"
    1990.6: "#C62828"
    1990.4: "#2E7D32"
    C_IV: "#2E7D32"
    C IV: "#2E7D32"
    IV: "#2E7D32"
    1990.4.a: "#004D40"
    C_IVA: "#004D40"
    C IVA: "#004D40"
    IV-A: "#004D40"
    1990.4.b1: "#00796B"
    C_IVB1: "#00796B"
    C IVB1: "#00796B"
    IV-B1: "#00796B"
    1990.4.b2: "#00838F"
    C_IVB2: "#00838F"
    C IVB2: "#00838F"
    IV-B2: "#00838F"
    1990.4.c: "#00BCD4"
    C_IVC: "#00BCD4"
    C IVC: "#00BCD4"
    IV-C: "#00BCD4"
    1990.4.d: "#42A5F5"
    C_IVD: "#42A5F5"
    C IVD: "#42A5F5"
    IV-D: "#42A5F5"
    1990.4.e: "#1976D2"
    C_IVE: "#1976D2"
    C IVE: "#1976D2"
    IV-E: "#1976D2"
    1990.4.f: "#0288D1"
    C_IVF: "#0288D1"
    C IVF: "#0288D1"
    IV-F: "#0288D1"
    1990.4.g: "#4FC3F7"
    C_IVG: "#4FC3F7"
    C IVG: "#4FC3F7"
    IV-G: "#4FC3F7"
    1990.4.h: "#4DB6AC"
    C_IVH: "#4DB6AC"
    C IVH: "#4DB6AC"
    IV-H: "#4DB6AC"
    1990.4.i: "#7E57C2"
    C_IVI: "#7E57C2"
    C IVI: "#7E57C2"
    IV-I: "#7E57C2"
    1990.4.j: "#5E35B1"
    C_IVJ: "#5E35B1"
    C IVJ: "#5E35B1"
    IV-J: "#5E35B1"
    1990.4.k: "#311B92"
    C_IVK: "#311B92"
    C IVK: "#311B92"
    IV-K: "#311B92"
    2000.1: "#689F38"
    2000.2: "#2E7D32"
    2000.3: "#33691E"
    2000.4: "#43A047"
    2000.5: "#9E9D24"
    2010.1: "#CDDC39"
    2010_human-like: "#CDDC39"
    2010 human-like: "#CDDC39"
    2010.2: "#FBC02D"
    2016_human-like: "#FBC02D"
    2016 human-like: "#FBC02D"
    Other-Avian: "#FFA726"
    Other-Avian-c1: "#FFA000"
    Other-Avian-c2: "#FF8F00"
    Other-Avian-c3: "#F57C00"
    Other-Avian-c4: "#FF6F00"
    Other-Canine-cAvian: "#E65100"
    Other-Canine: "#E65100"
    Other-Canine-cEquine: "#FFC107"
    Other-Equine: "#FFCC80"
    Other-Human-1960: "#546E7A"
    Other-Human-1970: "#8D6E63"
    Other-Human-1980: "#6D4C41"
    Other-Human-1990: "#424242"
    Other-Human-2000: "#455A64"
    Other-Human-2010: "#E65100"
    Other-Human-2020: "#EF6C00"
  N1:
    LAIV-Classical: "#EF9A9A"
    LAIV: "#EF9A9A"
    MN99: "#EF9A9A"
    N1.C.1.1: "#EF9A9A"
    classicalSwine: "#29B6F6"
    Classical: "#29B6F6"
    N1.C: "#29B6F6"
    N1.C.1: "#2196F3"
    N1.C.1.2: "#1565C0"
    N1.C.2: "#039BE5"
    N1.C.2.1: "#7E57C2"
    N1.C.3: "#512DA8"
    N1.C.3.1: "#1A237E"
    N1.C.3.2: "#303F9F"
    pdm: "#7CB342"
    PDM: "#7CB342"
    pandemic: "#7CB342"
    Pandemic: "#7CB342"
    N1.P: "#7CB342"
    N1-avian: "#FF8A65"
    N1.E: "#FF8A65"
    N1-avian-1: "#F4511E"
    N1-avian-2: "#E65100"
    N1-avian-3: "#F57C00"
    N1-avian-4: "#FF9800"
    N1.E.1: "#FF9800"
  N2:
    LAIV-98: "#EF9A9A"
    1998: "#8E24AA"
    98: "#8E24AA"
    1998A: "#AB47BC"
    98A: "#AB47BC"
    1998B: "#4A148C"
    98B: "#4A148C"
    2002: "#2196F3"
    02: "#2196F3"
    2002A: "#3F51B5"
    02A: "#3F51B5"
    2002B: "#283593"
    02B: "#283593"
    2016: "#4DB6AC"
    N2-EU-3: "#8BC34A"
    N2-EU-4: "#558B2F"
    N2-EU-5: "#1B5E20"
    N2-EU-6: "#AFB42B"
    N2g-1: "#2E7D32"
    N2g-2: "#FFB300"
    N2s: "#E64A19"
    humanSeasonal: "#424242"
    Human-seasonal: "#424242"
  internal:
    LAIV: "#EF9A9A"
    TX98: "#E53935"
    avian: "#FFB74D"
    M-avian: "#FFB74D"
    M-avian-spillover: "#FFB74D"
    NP-avian: "#FFB74D"
    NP-avian-spillover: "#FFB74D"
    NS-avian: "#FFB74D"
    NS-avian-spillover: "#FFB74D"
    PA-avian: "#FFB74D"
    PA-avian-spillover: "#FFB74D"
    PB1-avian: "#FFB74D"
    PB1-avian-spillover: "#FFB74D"
    PB2-avian: "#FFB74D"
    TRIG: "#1976D2"
    humanSeasonal: "#757575"
    Human-seasonal: "#757575"
    pdm: "#558B2F"
    PDM: "#558B2F"
    pandemic: "#558B2F"
    Pandemic: "#558B2F"
  PB2:
    LAIV: "#EF9A9A"
    TX98: "#E53935"
    avian: "#FFB74D"
    M-avian: "#FFB74D"
    M-avian-spillover: "#FFB74D"
    NP-avian: "#FFB74D"
    NP-avian-spillover: "#FFB74D"
    NS-avian: "#FFB74D"
    NS-avian-spillover: "#FFB74D"
    PA-avian: "#FFB74D"
    PA-avian-spillover: "#FFB74D"
    PB1-avian: "#FFB74D"
    PB1-avian-spillover: "#FFB74D"
    PB2-avian: "#FFB74D"
    TRIG: "#1976D2"
    humanSeasonal: "#757575"
    Human-seasonal: "#757575"
    pdm: "#558B2F"
    PDM: "#558B2F"
    pandemic: "#558B2F"
    Pandemic: "#558B2F"
  PB1:
    LAIV: "#EF9A9A"
    TX98: "#E53935"
    avian: "#FFB74D"
    M-avian: "#FFB74D"
    M-avian-spillover: "#FFB74D"
    NP-avian: "#FFB74D"
    NP-avian-spillover: "#FFB74D"
    NS-avian: "#FFB74D"
    NS-avian-spillover: "#FFB74D"
    PA-avian: "#FFB74D"
    PA-avian-spillover: "#FFB74D"
    PB1-avian: "#FFB74D"
    PB1-avian-spillover: "#FFB74D"
    PB2-avian: "#FFB74D"
    TRIG: "#1976D2"
    humanSeasonal: "#757575"
    Human-seasonal: "#757575"
    pdm: "#558B2F"
    PDM: "#558B2F"
    pandemic: "#558B2F"
    Pandemic: "#558B2F"
  PA:
    LAIV: "#EF9A9A"
    TX98: "#E53935"
    avian: "#FFB74D"
    M-avian: "#FFB74D"
    M-avian-spillover: "#FFB74D"
    NP-avian: "#FFB74D"
    NP-avian-spillover: "#FFB74D"
    NS-avian: "#FFB74D"
    NS-avian-spillover: "#FFB74D"
    PA-avian: "#FFB74D"
    PA-avian-spillover: "#FFB74D"
    PB1-avian: "#FFB74D"
    PB1-avian-spillover: "#FFB74D"
    PB2-avian: "#FFB74D"
    TRIG: "#1976D2"
    humanSeasonal: "#757575"
    Human-seasonal: "#757575"
    pdm: "#558B2F"
    PDM: "#558B2F"
    pandemic: "#558B2F"
    Pandemic: "#558B2F"
  NP:
    LAIV: "#EF9A9A"
    TX98: "#E53935"
    avian: "#FFB74D"
    M-avian: "#FFB74D"
    M-avian-spillover: "#FFB74D"
    NP-avian: "#FFB74D"
    NP-avian-spillover: "#FFB74D"
    NS-avian: "#FFB74D"
    NS-avian-spillover: "#FFB74D"
    PA-avian: "#FFB74D"
    PA-avian-spillover: "#FFB74D"
    PB1-avian: "#FFB74D"
    PB1-avian-spillover: "#FFB74D"
    PB2-avian: "#FFB74D"
    TRIG: "#1976D2"
    humanSeasonal: "#757575"
    Human-seasonal: "#757575"
    pdm: "#558B2F"
    PDM: "#558B2F"
    pandemic: "#558B2F"
    Pandemic: "#558B2F"
  M:
    LAIV: "#EF9A9A"
    TX98: "#E53935"
    avian: "#FFB74D"
    M-avian: "#FFB74D"
    M-avian-spillover: "#FFB74D"
    NP-avian: "#FFB74D"
    NP-avian-spillover: "#FFB74D"
    NS-avian: "#FFB74D"
    NS-avian-spillover: "#FFB74D"
    PA-avian: "#FFB74D"
    PA-avian-spillover: "#FFB74D"
    PB1-avian: "#FFB74D"
    PB1-avian-spillover: "#FFB74D"
    PB2-avian: "#FFB74D"
    TRIG: "#1976D2"
    humanSeasonal: "#757575"
    Human-seasonal: "#757575"
    pdm: "#558B2F"
    PDM: "#558B2F"
    pandemic: "#558B2F"
    Pandemic: "#558B2F"
  NS:
    LAIV: "#EF9A9A"
    TX98: "#E53935"
    avian: "#FFB74D"
    M-avian: "#FFB74D"
    M-avian-spillover: "#FFB74D"
    NP-avian: "#FFB74D"
    NP-avian-spillover: "#FFB74D"
    NS-avian: "#FFB74D"
    NS-avian-spillover: "#FFB74D"
    PA-avian: "#FFB74D"
    PA-avian-spillover: "#FFB74D"
    PB1-avian: "#FFB74D"
    PB1-avian-spillover: "#FFB74D"
    PB2-avian: "#FFB74D"
    TRIG: "#1976D2"
    humanSeasonal: "#757575"
    Human-seasonal: "#757575"
    pdm: "#558B2F"
    PDM: "#558B2F"
    pandemic: "#558B2F"
    Pandemic: "#558B2F"
